language: python

python:
  - "3.6"

install: 
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install nose

script:
  - python manage.py db init
  - python manage.py db migrate
  - python manage.py db upgrade
  - python manage.py test --coverage
  - nosetests --with-coverage --cover-package=app

after_success:
  - coveralls